FEM:
  poisson_ratio: 0.25
  traction_bs_F:
  - 0
  - -1
  traction_bs_x: -1
  traction_bs_y1: 0.4
  traction_bs_y2: 0.6
  youngs_modulus: 100
adaptive_penalty:
  alpha: 0.9
  epsilon: 1.0e-08
  gamma: 0.01
args_str: vars.n_points_surface=512 problem_sampling.n_points_envelope=1024 lambda_scc=10
  ph.scc_n_grid_points=32
curvature_expression: 4*H**2 - 2*K
curvature_pts_source: surface
curvature_use_gradnorm_weights: false
data:
  data_dir: /system/user/publicdata/simjeb_preprocessed/occ_sds
  simjeb_ids: []
decay_steps: 5000
dirichlet_use_surface_points: true
div_neighbor_agg_fn: min
div_norm_order: 1
diversity_pts_source: domain
exclude_surface_points_close_to_interface_cutoff: 0.025
field_losses:
- comp
- vol
- chamfer_div
- wasserstein_div
ginn_bsize: 1
gpu_list: 0
grad_clipping:
  auto_clip_hist_len: 50
  auto_clip_min_len: 50
  auto_clip_on: true
  auto_clip_percentile: 0.8
  grad_clip: 0.5
  grad_clipping_on: true
lambda_chamfer_div: 0
lambda_comp: 0
lambda_curv: 1
lambda_data: 0.0
lambda_dirichlet: 0.0
lambda_div: 1.0
lambda_eikonal: 1
lambda_env: 1
lambda_if: 1
lambda_if_normal: 1
lambda_lip: 0.0
lambda_obst: 0
lambda_rotsym: 0
lambda_scc: 10
lambda_vol: 0
latent_sampling:
  ginn_bsize: 1
  nz: 1
  val_plot_grid:
  - 1
  - 1
  z_sample_interval:
  - 0
  - 0.1
  z_sample_method: equidistant
level_set: 0.0
load_model: false
load_mos: false
load_optimizer: false
load_scheduler: false
log_level: INFO
lr: 0.001
max_curv: 0
max_div: -0.03
max_epochs: 3000
meshing:
  level_set: 0.0
  mc_chunks: 1
  mc_resolution: 128
  mesh_reduction: 0.9
  nf_is_density: false
metrics:
  chamfer_metrics_vectorize: true
  metrics_chamfer_orders:
  - 2
  metrics_diversity_inner_agg_fns:
  - sum
  metrics_diversity_n_samples: 1000
  metrics_diversity_outer_agg_fns:
  - sum
  metrics_diversity_ps:
  - 0.5
  shape_metrics_every_n_epochs: 1000000
  val_shape_metrics_every_n_epochs: 1000000
model:
  density_iso_level: 0.05
  group_size_fwd_no_grad: 2097152
  layers:
  - 3
  - 64
  - 64
  - 64
  - 1
  model_str: cond_wire
  nx: 2
  ny: 1
  nz: 1
  return_density: false
  use_density: false
  w0: 1.0
  w0_initial: 18
  wire_scale: 6
model_save_path: path/to/dir
n_points_data: -1
nf_is_density: false
num_workers: 1
nx: 2
nz: 1
objective: curv
opt: adam
overwrite_existing_saved_model: true
ph:
  evaluate_ph_grid_per_shape: true
  ginn_bsize: 1
  is_density: false
  iso_level: -0.0
  nx: 2
  ph_1_hole_level: 0.1
  ph_loss_maxdim: 1
  ph_loss_sub0_points: false
  ph_loss_super0_points: false
  ph_loss_target_betti:
  - 1
  - 1
  - 0
  ph_max_num_workers: 16
  problem_str: wheel
  scc_n_grid_points: 32
  scc_penalty_norm_eps: 0.0001
  simjeb_root_dir: GINN/simJEB/data
plot:
  fig_size:
  - 12
  - 7
  fig_wandb: true
  level_set: 0.0
  plot_2d_resolution: 100
  problem_str: wheel
  show_colorbar: true
  val_plot_grid:
  - 1
  - 1
plot_every_n_epochs: 50
plot_ph_diagram: true
plot_shape: true
plot_surface_points: true
plot_surface_pts_every_n_epochs: 100
problem:
  plot_2d_resolution: 100
  problem_str: wheel
  rotation_n_cycles: 1
  simjeb_root_dir: GINN/simJEB/data
problem_sampling:
  n_points_domain: 512
  n_points_envelope: 1024
  n_points_interfaces: 512
  n_points_normals: 512
  n_points_rotation_symmetric: 512
  n_points_surface: 512
  nx: 2
reset_zlatents_every_n_epochs: 1
save_every_n_epochs: 100
save_model_dir: path/to/dir/cond_wire/2026_01_28__15_28_49-no_wandb_id
save_optimizer: true
scale_chamfer_div: 1
scale_comp: 1
scale_curv: 0.001
scale_div: 1.0
scale_eikonal: 0.1
scale_vol: 1
scheduler_gamma: 0.5
seed: 11
strain_curvature_clip_max: 1000000.0
surface:
  bin_search_steps: 10
  do_numerical_surface_points: false
  do_uniform_resampling: true
  equidistant_init_grid: true
  level_set: 0.0
  n_points_surface: 512
  nx: 2
  recompute_every_n_epochs: 1
  surf_pts_converged_interval: 1
  surf_pts_do_uniform_resampling: true
  surf_pts_inflate_bounds_amount: 0.05
  surf_pts_lr: 0.01
  surf_pts_n_iter: 10
  surf_pts_newton_clip: 0.15
  surf_pts_prec_eps: 0.001
  surf_pts_surpress_tqdm: true
  surf_pts_uniform_min_count: 1000
  surf_pts_uniform_n_iter: 10
  surf_pts_uniform_n_iter_reproj: 5
  surf_pts_uniform_nof_neighbours: 16
  surf_pts_uniform_prec_eps: 0.001
  surf_pts_uniform_reproject_surpress_tqdm: true
  surf_pts_uniform_stepsize: 0.75
  surf_pts_use_newton: true
timer:
  accumulate: true
  print: false
timer_accumulate: true
timer_print: false
train_plot_max_n_shapes: 1
use_augmented_lagrangian: true
use_scheduler: false
val_plot_shape: true
valid_every_n_epochs: 1000
wandb_entity_name: abra
wandb_experiment_name: donut_cond_wire
wandb_id: no_wandb_id
wandb_project_name: topginn
weight_rescale_alpha: 0.9
weight_rescale_interval: 100
weight_rescale_on: false
