###################
## Model
###################
wandb_experiment_name: 'donut_cond_wire'

# put all reused variables into vars
vars:
  nx: 2 # input is 2D
  nz: 1 # dimension of the modulation vector (1D latent space for single shape)
  ginn_bsize: 1 # train single model to avoid OOM
  val_plot_grid: [1, 1] # [n_first_dims, shapes_per_dim]
  problem_str: 'wheel'
  ginn_on: 1
  n_points_surface: 512
  nf_is_density: False
  level_set: 0.0

# useful global variables
nx: ${vars.nx}
nz: ${vars.nz}
ginn_bsize: ${vars.ginn_bsize}
level_set: ${vars.level_set}
nf_is_density: ${vars.nf_is_density}


model:
  model_str: 'cond_wire'
  nx: ${vars.nx}
  nz: ${vars.nz}
  return_density: ${vars.nf_is_density}
  w0_initial: 18
  wire_scale: 6
  layers: [64,64,64]  # smaller layers to save memory

reset_zlatents_every_n_epochs: 1
latent_sampling:
  nz: ${vars.nz}
  ginn_bsize: ${vars.ginn_bsize}
  z_sample_method: 'equidistant'
  val_plot_grid: ${vars.val_plot_grid}
  z_sample_interval: [0,0.1]


###################
## Data
###################
data:
  simjeb_ids: []

###################
## GINN
###################
train_plot_max_n_shapes: 1
plot_every_n_epochs: 50
valid_every_n_epochs: 1000

###################
## Loss-balancing
###################
## Data losses
lambda_data: 0.0e+1
lambda_lip: ${eval:1.0e-7 * 0}
lambda_dirichlet: ${eval:1.0e1 * 0}
dirichlet_use_surface_points: True

## GINN losses
objective: 'curv'
### local
lambda_if: ${eval:${vars.ginn_on} * 1}
lambda_env: ${eval:${vars.ginn_on} * 1}
lambda_obst: ${eval:${vars.ginn_on} * 0}
lambda_if_normal: ${eval:${vars.ginn_on} * 1}
### global
lambda_eikonal: ${eval:${vars.ginn_on} * 1}
lambda_scc: ${eval:${vars.ginn_on} * 10}  # topology constraint
lambda_curv: 1
lambda_div: 0.0  # disable diversity loss for single shape training
lambda_rotsym: 0  # disable rotation symmetry constraint

max_curv: 0
max_div: -0.03

scale_curv: 1.0e-3
scale_div: 1.0
scale_chamfer_div: 1
scale_vol: 1
scale_comp: 1
scale_eikonal: 0.1

###################
## SCC algorithm
###################
ph:
  nx: ${vars.nx}
  problem_str: ${vars.problem_str}
  ginn_bsize: ${vars.ginn_bsize}
  is_density: ${vars.nf_is_density}
  iso_level: -0.00
  ph_1_hole_level: 0.1
  ph_loss_maxdim: 1
  ph_loss_target_betti: [1, 1, 0]  # [b0=1 component, b1=1 hole, b2=0]
  scc_penalty_norm_eps: 1.0e-4
  scc_n_grid_points: 32  # reduced from 64 to save memory
  evaluate_ph_grid_per_shape: True

###################
## Surface points
###################
surface:
  nx: ${vars.nx}
  n_points_surface: ${vars.n_points_surface}
  level_set: ${vars.level_set}
  do_numerical_surface_points: False
  bin_search_steps: 10
  equidistant_init_grid: True
  do_uniform_resampling: True
  recompute_every_n_epochs: 1

###################
## DIVERSITY
###################
diversity_pts_source: domain
div_norm_order: 1

###################
## LOGGING
###################
log_level: 'INFO'

## Multi-processing
num_workers: ${eval:min(${vars.ginn_bsize},8)}

## Plotting
plot:
  val_plot_grid: ${vars.val_plot_grid}
  problem_str: ${vars.problem_str}
  fig_size: [12, 7]
  level_set: ${vars.level_set}
  show_colorbar: True

## Specific plots
plot_shape: True
val_plot_shape: True
plot_surface_points: True
plot_ph_diagram: True
plot_surface_pts_every_n_epochs: 100

## Timer
timer:
  print: False
  accumulate: True

###################
## Problem
###################
problem:
  problem_str: ${vars.problem_str}
  rotation_n_cycles: 1  # minimum value required
  plot_2d_resolution: 100

problem_sampling:
  nx: ${vars.nx}
  n_points_domain: 512
  n_points_envelope: 1024  # reduced from 2048
  n_points_interfaces: 512
  n_points_normals: 512
  n_points_surface: ${vars.n_points_surface}
  n_points_rotation_symmetric: 512

meshing:
  level_set: ${vars.level_set}
  nf_is_density: ${vars.nf_is_density}
  mc_resolution: 128
  mesh_reduction: 0.9

###################
## Training
###################
max_epochs: 3000  # reduced from 5000
lr: 0.001
opt: adam

use_scheduler: False
scheduler_gamma: 0.5
decay_steps: 5000

grad_clipping:
  grad_clipping_on: True
  grad_clip: 0.5
  auto_clip_on: True
  auto_clip_percentile: 0.8
  auto_clip_hist_len: 50
  auto_clip_min_len: 50

## Weight saving
model_save_path: 'path/to/dir'
save_every_n_epochs: 100
overwrite_existing_saved_model: True
save_optimizer: True

## Weight loading
load_mos: False
load_model: False
load_optimizer: False
load_scheduler: False
